export const WORKER_ACTION_NAMES = {
  SET_WORKERS: "SET_WORKERS",
  LOAD_WORKER: "LOAD_WORKER",
  LOAD_WORKERS: "LOAD_WORKERS"
};

export const CONTACT_ACTION_NAMES = {
  SET_CONTACTS: "SET_CONTACTS",
  LOAD_CONTACT: "LOAD_CONTACT"
};

export const PROJECT_ACTION_NAMES = {
  SET_PROJECTS: "SET_PROJECTS",
  LOAD_PROJECTS: "LOAD_PROJECTS",
  LOAD_PROJECT: "LOAD_PROJECT"
};

export const ERROR_ACTION_NAMES = {
  SET_ERROR: "SET_ERROR"
};
