export const WORKER_ACTION_NAMES = {
  SET_WORKERS: "SET_WORKERS",
  LOAD_WORKER: "LOAD_WORKER",
  LOAD_WORKERS: "LOAD_WORKERS"
};

export const CONTACT_ACTION_NAMES = {
  SET_CONTACTS: "SET_CONTACTS",
  LOAD_CONTACT: "LOAD_CONTACT"
};

export const PROJECT_ACTION_NAMES = {
  SET_PROJECTS: "SET_PROJECTS",
  LOAD_PROJECTS: "LOAD_PROJECTS",
  LOAD_PROJECT: "LOAD_PROJECT"
};

export const CITY_ACTION_NAMES = {
  SET_CITIES: "SET_CITIES",
  LOAD_CITIES: "LOAD_CITIES"
};

export const COUNTRY_ACTION_NAMES = {
  SET_COUNTRIES: "SET_COUNTRIES",
  LOAD_COUNTRIES: "LOAD_COUNTRIES"
};

export const ERROR_ACTION_NAMES = {
  SET_ERROR: "SET_ERROR"
};
