export const WORKER_ACTION_NAMES = {
  SET_WORKERS: "SET_WORKERS",
  LOAD_WORKER: "LOAD_WORKER"
};

export const CONTACT_ACTION_NAMES = {
  SET_CONTACTS: "SET_CONTACTS",
  LOAD_CONTACT: "LOAD_CONTACT"
};

export const PROJECT_ACTION_NAMES = {
  SET_PROJECTS: "SET_PROJECTS",
  LOAD_PROJECTS: "LOAD_PROJECTS"
};

export const ERROR_ACTION_NAMES = {
  SET_ERROR: "SET_ERROR"
};
